//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDEF.Web.UserDefine {
    
    public partial class EditCustomField_First {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.LinkButton lb_Save;
        protected System.Web.UI.WebControls.TextBox FieldColumnID;
        protected System.Web.UI.WebControls.DropDownList FieldDataType;
        protected System.Web.UI.WebControls.DropDownList FieldSelectType;
        protected System.Web.UI.WebControls.TextBox txtDetails;
        protected System.Web.UI.WebControls.TextBox FieldColumnName;
        protected System.Web.UI.WebControls.TextBox FieldColumnText;
        protected System.Web.UI.WebControls.TextBox FieldDefaultValue;
        protected System.Web.UI.WebControls.TextBox FieldRemark;
    }
}
