//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDEF.Web.UserDefine {
    
    public partial class EditColumnViewExpression {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.LinkButton lb_Save;
        protected System.Web.UI.WebControls.TextBox FieldExpressionID;
        protected System.Web.UI.WebControls.DropDownList FieldUseDataType;
        protected System.Web.UI.WebControls.DropDownList FieldExpressionName;
        protected System.Web.UI.WebControls.CheckBox FieldUseTag;
        protected System.Web.UI.WebControls.CheckBox FieldStopTag;
    }
}
