//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDEF.Web.UserDefine {
    
    public partial class EditCustomSelectType {
        protected System.Web.UI.HtmlControls.HtmlHead Head2;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.TextBox FieldSelectTypeID;
        protected System.Web.UI.WebControls.TextBox FieldSelectTypeText;
        protected System.Web.UI.WebControls.TextBox FieldRemark;
    }
}
