//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDEF.Web.UserDefine {
    
    public partial class ListColumnViewExpression {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.LinkButton btnRefresh;
        protected System.Web.UI.WebControls.TextBox SearchExpressionName;
        protected System.Web.UI.WebControls.TextBox SearchExpressionValue;
        protected System.Web.UI.WebControls.DropDownList SearchUseDataType;
        protected System.Web.UI.WebControls.GridView GridView1;
    }
}
